name: flutter_note_app
description: 오준석님의 강의 이어서

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  sqflite: ^2.0.2
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  freezed: ^1.1.1
  build_runner: ^2.1.7
  sqflite_common_ffi: ^2.1.0+2

flutter:

  uses-material-design: true
